### ISSUE TITLE
Curse of Echoes always playing

### ISSUE THREAD

**Issue by lgnmcrules** [Darkhax-Minecraft/Cursed#24] opened 2021-05-24 20:02 UTC
In a world that is frequently played on with this mod, the Curse of Echoes will be constantly playing to all players.  This is regardless of position in the world, if you have any cursed items, or if there are any living entities nearby.  
Attempted solutions have been to try and kill all entities in hopes that one of them was just wearing a piece of armor with it using the "/kill @e" command, restarting the server, and deleting chunks where the issue was first noticed.

**Comment by Darkhax** [comment] 2021-05-24 20:07
Thanks for reporting, this is a duplicate of https://github.com/Darkhax-Minecraft/Cursed/issues/23 and is being worked on.

**Closed as completed by Darkhax** 2021-05-24 20:07 UTC
